services:
  - type: web
    name: weather-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_WEATHER_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 